import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SubscriptionProvider } from "@/components/SubscriptionContext";
import { BetSlipProvider } from "@/components/social/BetSlipContext";
import { BetSlip } from "@/components/social/BetSlip";
import JarvisChat from "@/components/chat/JarvisChat";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SubscriptionProvider>
          <BetSlipProvider>
            {children}
            <BetSlip />
            <JarvisChat />
          </BetSlipProvider>
        </SubscriptionProvider>
      </body>
    </html>
  );
}
