import React from 'react';
import { AlertTriangle, CheckCircle2 } from 'lucide-react';

interface DisclaimerModalProps {
    onAccept: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ onAccept }) => {
    return (
        <div className="fixed inset-0 z-50 bg-slate-900/95 flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl overflow-hidden border border-slate-700">
                {/* Header */}
                <div className="bg-slate-800 p-6 flex items-center gap-4">
                    <AlertTriangle className="w-10 h-10 text-white" />
                    <div>
                        <h2 className="text-2xl font-bold text-white">Legal Liability Disclaimer</h2>
                        <p className="text-red-100 text-sm">Please read carefully before proceeding.</p>
                    </div>
                </div>

                {/* Content */}
                <div className="p-8 space-y-4 max-h-[60vh] overflow-y-auto text-slate-700">
                    <p className="font-bold">1. No Attorney-Client Relationship</p>
                    <p className="text-sm">
                        Use of Legal Eagle ("The Application") does not create an attorney-client
                        relationship between you and the creators of The Application. The Application
                        is an automated tool powered by artificial intelligence and is not a substitute
                        for the advice of an attorney.
                    </p>

                    <p className="font-bold">2. Not Legal Advice</p>
                    <p className="text-sm">
                        The content, scores, and recommendations generated by The Application are for
                        informational purposes only. They do not constitute legal advice. You should
                        not act or refrain from acting on the basis of any content included in this
                        site without seeking legal or other professional advice.
                    </p>

                    <p className="font-bold">3. Limitation of Liability</p>
                    <p className="text-sm">
                        THE APPLICATION IS PROVIDED "AS IS". THE CREATORS EXPRESSLY DISCLAIM ALL
                        LIABILITY IN RESPECT TO ACTIONS TAKEN OR NOT TAKEN BASED ON ANY OR ALL THE
                        CONTENTS OF THIS APPLICATION. IN NO EVENT SHALL THE CREATORS BE LIABLE FOR
                        ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES
                        ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THIS APPLICATION.
                    </p>

                    <p className="font-bold">4. Accuracy of AI</p>
                    <p className="text-sm">
                        Artificial Intelligence models can hallucinate facts, cite non-existent case
                        law, or misinterpret statutes. All output must be verified by a qualified
                        human professional.
                    </p>

                    <p className="font-bold">5. Confidentiality Warning</p>
                    <p className="text-sm">
                        Documents uploaded to this application may be processed by third-party AI
                        services. Do not upload documents containing attorney-client privileged
                        information without understanding the confidentiality implications.
                    </p>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-slate-200 bg-slate-50 flex justify-end">
                    <button
                        onClick={onAccept}
                        className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-lg font-bold shadow-lg transition-all transform hover:scale-105 active:scale-95 flex items-center gap-2"
                    >
                        <CheckCircle2 className="w-5 h-5" />
                        I Understand & Agree
                    </button>
                </div>
            </div>
        </div>
    );
};

export default DisclaimerModal;
