[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/icebreaker"
  to = "https://sentaient-icebreaker-857.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/icebreaker/*"
  to = "https://sentaient-icebreaker-857.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/icebusiness"
  to = "https://sentaient-icebusiness-hub.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/icebusiness/*"
  to = "https://sentaient-icebusiness-hub.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/iceadmin"
  to = "https://sentaient-iceadmin-hub.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/iceadmin/*"
  to = "https://sentaient-iceadmin-hub.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/legaleagle/*"
  to = "/legaleagle/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
