import type { Theme } from '@/types';

export const THEMES: Record<string, Theme> = {
    navy: {
        id: 'navy',
        name: 'Navy',
        sidebar: 'bg-slate-900 border-slate-800',
        sidebarText: 'text-slate-400',
        activeNav: 'bg-white/10 text-white',
        appBg: 'bg-slate-100',
        panelBg: 'bg-white border-slate-200',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-slate-200',
        accent: 'bg-blue-700 hover:bg-blue-800',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-slate-500 hover:text-slate-700 hover:bg-slate-100',
        toggleActive: 'bg-slate-800 text-white shadow',
        toggleInactive: 'text-slate-500 hover:text-slate-700',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-700',
        roastTitle: 'text-red-400',
        roastText: 'text-red-50',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    dark: {
        id: 'dark',
        name: 'Midnight',
        sidebar: 'bg-slate-950 border-slate-900',
        sidebarText: 'text-slate-400',
        activeNav: 'bg-blue-900/30 text-blue-400',
        appBg: 'bg-slate-950',
        panelBg: 'bg-slate-900 border-slate-800',
        panelText: 'text-slate-300',
        card: 'bg-slate-900 border-slate-800 text-slate-200',
        docBg: 'bg-slate-900',
        docText: 'text-slate-200',
        docBorder: 'border-slate-800',
        main: 'bg-slate-950',
        accent: 'bg-blue-600 hover:bg-blue-500',
        heatmapCritical: 'bg-red-900/30 text-red-200 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-900/30 text-orange-200 border-b-2 border-orange-500',
        buttonSecondary: 'text-slate-400 hover:text-white hover:bg-white/5',
        toggleActive: 'bg-blue-600 text-white shadow',
        toggleInactive: 'text-slate-500 hover:text-slate-300',
        roastBg: 'bg-red-950/80',
        roastBorder: 'border-red-600/50',
        roastTitle: 'text-red-400',
        roastText: 'text-red-50',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-400 hover:text-white',
        comparisonBoxCurrent: 'bg-red-900/20 border border-red-800 text-red-100',
        comparisonBoxProposed: 'bg-emerald-900/20 border border-emerald-800 text-emerald-100',
        citation: 'text-blue-300',
        detailHeader: 'text-white',
        roastTitleRed: 'text-red-400',
        selectedIssue: 'bg-blue-900/20 border-blue-700 ring-blue-500 ring-2',
        selectedIssueRoast: 'bg-red-900/20 border-red-700 ring-red-500 ring-2',
    },
    gray: {
        id: 'gray',
        name: 'Slate',
        sidebar: 'bg-gray-950 border-gray-900',
        sidebarText: 'text-gray-400',
        activeNav: 'bg-gray-800 text-gray-100',
        main: 'bg-gray-950',
        appBg: 'bg-gray-950',
        panelBg: 'bg-gray-900 border-gray-800',
        panelText: 'text-gray-300',
        card: 'bg-gray-900 border-gray-800 text-gray-300',
        docBg: 'bg-gray-950',
        docText: 'text-gray-300',
        docBorder: 'border-gray-800',
        accent: 'bg-gray-700 hover:bg-gray-600',
        icon: 'bg-gray-800 text-white',
        heatmapCritical: 'bg-red-900/30 text-red-200 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-900/30 text-orange-200 border-b-2 border-orange-500',
        buttonSecondary: 'text-gray-400 hover:text-gray-100 hover:bg-gray-800',
        toggleActive: 'bg-gray-700 text-white shadow',
        toggleInactive: 'text-gray-500 hover:text-gray-300',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-800',
        roastTitle: 'text-red-400',
        roastText: 'text-gray-100',
        roastIcon: 'text-red-600/20',
        roastShareBtn: 'text-red-400 hover:text-white',
        comparisonBoxCurrent: 'bg-red-900/20 border border-red-800 text-red-100',
        comparisonBoxProposed: 'bg-emerald-900/20 border border-emerald-800 text-emerald-100',
        citation: 'text-blue-300',
        detailHeader: 'text-white',
        roastTitleRed: 'text-red-400',
        selectedIssue: 'bg-gray-700 border-gray-600 ring-gray-500 ring-2',
        selectedIssueRoast: 'bg-red-900/20 border-red-700 ring-red-500 ring-2',
    },
    eggshell: {
        id: 'eggshell',
        name: 'Eggshell',
        sidebar: 'bg-[#F3F0E7] border-[#E6E2D6]',
        sidebarText: 'text-stone-600',
        activeNav: 'bg-[#E6E2D6] text-stone-900',
        appBg: 'bg-[#FAF9F6]',
        panelBg: 'bg-[#FDFBF7] border-[#E6E2D6]',
        panelText: 'text-stone-800',
        docBg: 'bg-white',
        docText: 'text-stone-900',
        docBorder: 'border-[#E6E2D6]',
        main: 'bg-[#FAF9F6]',
        accent: 'bg-stone-600 hover:bg-stone-700',
        heatmapCritical: 'bg-red-50 text-red-900 border-b-2 border-red-400',
        heatmapHigh: 'bg-orange-50 text-orange-900 border-b-2 border-orange-400',
        buttonSecondary: 'text-stone-500 hover:text-stone-800 hover:bg-[#E6E2D6]',
        toggleActive: 'bg-white shadow text-stone-900 border border-stone-200',
        toggleInactive: 'text-stone-500 hover:text-stone-700',
        roastBg: 'bg-red-50',
        roastBorder: 'border-red-200',
        roastTitle: 'text-red-700',
        roastText: 'text-slate-900',
        roastIcon: 'text-red-500/10',
        roastShareBtn: 'text-red-600 hover:text-red-800',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-800',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    burgundy: {
        id: 'burgundy',
        name: 'Burgundy',
        sidebar: 'bg-rose-950 border-rose-900',
        sidebarText: 'text-rose-200/70',
        activeNav: 'bg-rose-900/50 text-white',
        appBg: 'bg-rose-50/20',
        panelBg: 'bg-white border-rose-100',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-rose-100',
        main: 'bg-rose-50/30',
        accent: 'bg-rose-800 hover:bg-rose-700',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-rose-800/70 hover:text-rose-900 hover:bg-rose-50',
        toggleActive: 'bg-rose-800 text-white shadow',
        toggleInactive: 'text-rose-400 hover:text-rose-600',
        roastBg: 'bg-red-950',
        roastBorder: 'border-rose-800',
        roastTitle: 'text-rose-300',
        roastText: 'text-white',
        roastIcon: 'text-rose-500/30',
        roastShareBtn: 'text-rose-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    purple: {
        id: 'purple',
        name: 'Royal Purple',
        sidebar: 'bg-indigo-950 border-indigo-900',
        sidebarText: 'text-indigo-200/70',
        activeNav: 'bg-indigo-900/50 text-white',
        appBg: 'bg-indigo-50/20',
        panelBg: 'bg-white border-indigo-100',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-indigo-100',
        main: 'bg-indigo-50/30',
        accent: 'bg-indigo-700 hover:bg-indigo-600',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-indigo-700/70 hover:text-indigo-900 hover:bg-indigo-50',
        toggleActive: 'bg-indigo-700 text-white shadow',
        toggleInactive: 'text-indigo-400 hover:text-indigo-600',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-800',
        roastTitle: 'text-red-300',
        roastText: 'text-white',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    royalBlue: {
        id: 'royalBlue',
        name: 'Royal Blue',
        sidebar: 'bg-blue-900 border-blue-800',
        sidebarText: 'text-blue-200/80',
        activeNav: 'bg-blue-800 text-white',
        appBg: 'bg-blue-50/30',
        panelBg: 'bg-white border-blue-100',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-blue-100',
        main: 'bg-blue-50/30',
        accent: 'bg-blue-700 hover:bg-blue-600',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-blue-700/70 hover:text-blue-900 hover:bg-blue-50',
        toggleActive: 'bg-blue-700 text-white shadow',
        toggleInactive: 'text-blue-400 hover:text-blue-600',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-800',
        roastTitle: 'text-red-300',
        roastText: 'text-white',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    forest: {
        id: 'forest',
        name: 'Forest',
        sidebar: 'bg-emerald-950 border-emerald-900',
        sidebarText: 'text-emerald-200/70',
        activeNav: 'bg-emerald-900/50 text-white',
        appBg: 'bg-emerald-50/20',
        panelBg: 'bg-white border-emerald-100',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-emerald-100',
        main: 'bg-emerald-50/30',
        accent: 'bg-emerald-800 hover:bg-emerald-700',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-emerald-800/70 hover:text-emerald-900 hover:bg-emerald-50',
        toggleActive: 'bg-emerald-800 text-white shadow',
        toggleInactive: 'text-emerald-600 hover:text-emerald-800',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-800',
        roastTitle: 'text-red-300',
        roastText: 'text-white',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    sand: {
        id: 'sand',
        name: 'Dune',
        sidebar: 'bg-[#D8D0C0] border-[#C8BFAD]',
        sidebarText: 'text-stone-800',
        activeNav: 'bg-[#C8BFAD] text-stone-950',
        appBg: 'bg-[#F2EFE9]',
        panelBg: 'bg-white border-[#D8D0C0]',
        panelText: 'text-stone-800',
        docBg: 'bg-white',
        docText: 'text-stone-900',
        docBorder: 'border-[#D8D0C0]',
        main: 'bg-[#F2EFE9]',
        accent: 'bg-stone-600 hover:bg-stone-700',
        heatmapCritical: 'bg-red-50 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-50 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-stone-600 hover:text-stone-900 hover:bg-[#E6E2D6]',
        toggleActive: 'bg-[#D8D0C0] text-stone-900 shadow-sm',
        toggleInactive: 'text-stone-500 hover:text-stone-700',
        roastBg: 'bg-red-50',
        roastBorder: 'border-red-200',
        roastTitle: 'text-red-700',
        roastText: 'text-slate-900',
        roastIcon: 'text-red-500/10',
        roastShareBtn: 'text-red-600 hover:text-red-800',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-800',
        detailHeader: 'text-stone-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-1',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    },
    colorful: {
        id: 'colorful',
        name: 'Executive',
        sidebar: 'bg-gradient-to-br from-slate-900 via-[#1e293b] to-blue-950 border-slate-800',
        sidebarText: 'text-slate-300',
        activeNav: 'bg-white/10 text-white',
        appBg: 'bg-slate-50',
        panelBg: 'bg-white border-slate-200',
        panelText: 'text-slate-800',
        docBg: 'bg-white',
        docText: 'text-slate-900',
        docBorder: 'border-slate-200',
        main: 'bg-slate-50',
        accent: 'bg-blue-700 hover:bg-blue-600',
        heatmapCritical: 'bg-red-100 text-red-900 border-b-2 border-red-500',
        heatmapHigh: 'bg-orange-100 text-orange-900 border-b-2 border-orange-500',
        buttonSecondary: 'text-slate-600 hover:text-slate-900 hover:bg-slate-100',
        toggleActive: 'bg-blue-700 text-white shadow',
        toggleInactive: 'text-slate-500 hover:text-slate-700',
        roastBg: 'bg-red-950',
        roastBorder: 'border-red-800',
        roastTitle: 'text-red-300',
        roastText: 'text-white',
        roastIcon: 'text-red-500/20',
        roastShareBtn: 'text-red-300 hover:text-white',
        comparisonBoxCurrent: 'bg-red-50/50 border border-red-100 text-slate-800',
        comparisonBoxProposed: 'bg-emerald-50/50 border border-emerald-100 text-slate-800',
        citation: 'text-blue-700',
        detailHeader: 'text-slate-900',
        roastTitleRed: 'text-red-800',
        selectedIssue: 'bg-blue-50/50 border-blue-400 ring-blue-200 ring-2',
        selectedIssueRoast: 'bg-red-100/50 border-red-500 ring-red-200 ring-2',
    }
};

export const DEFAULT_THEME = THEMES.navy;
