// Generated by Aria-Icons (https://icons.leularia.com)
// Collection: heroicons | Name: x-mark
import React from 'react';

export const CloseIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    className={className}
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
    {...props}
  >
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
  </svg>
);
