// Generated by Aria-Icons (https://icons.leularia.com)
// Collection: heroicons | Name: lightning-bolt
import React from 'react';

export const LightningIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    className={className}
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
    {...props}
  >
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
  </svg>
);
