// Generated by Aria-Icons (https://icons.leularia.com)
// Collection: heroicons | Name: bulls-eye
import React from 'react';

export const TargetIcon = ({ size = 24, className = '', ...props }) => (
  <svg width={size} height={size} className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
  </svg>
);
