import React, { useState } from 'react';
import { LiveKitRoom, RoomAudioRenderer, VoiceAssistantControlBar, useVoiceAssistant } from '@livekit/components-react';
import '@livekit/components-styles';
import { Bot, Mic, MicOff } from 'lucide-react';

/**
 * VoiceAgent.jsx
 * Real-time Voice AI Consultant using LiveKit Cloud.
 */
export default function VoiceAgent({ roomToken, serverUrl }) {
    const [isConnected, setIsConnected] = useState(false);

    // If no token is provided, we render a placeholder state.
    // In production, the token is generated by a secure backend upon user request.
    if (!roomToken || !serverUrl) {
        return (
            <div className="p-6 bg-slate-900 border border-slate-800 rounded-xl flex flex-col items-center gap-4 text-center">
                <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center border border-slate-700">
                    <Bot size={32} className="text-slate-400" />
                </div>
                <div>
                    <h3 className="text-slate-100 font-bold">AI Voice Consultant</h3>
                    <p className="text-slate-400 text-xs mt-1 max-w-[250px]">
                        Speak directly with the agent orchestrator to review your conversion funnel live.
                    </p>
                </div>
                <button 
                    className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-semibold rounded-lg transition-colors"
                    onClick={() => alert("In production, this requests a secure LiveKit token from the backend.")}
                >
                    Connect Voice
                </button>
            </div>
        );
    }

    return (
        <LiveKitRoom
            serverUrl={serverUrl}
            token={roomToken}
            connect={isConnected}
            audio={true}
            video={false}
            className="w-full bg-slate-900 rounded-xl border border-slate-800 p-4"
        >
            <div className="flex flex-col items-center gap-4">
                <VoiceAssistantStatus />
                <VoiceAssistantControlBar />
                <RoomAudioRenderer />
            </div>
        </LiveKitRoom>
    );
}

function VoiceAssistantStatus() {
    const { state, audioTrack } = useVoiceAssistant();
    return (
        <div className="flex items-center gap-3">
            <div className={`w-3 h-3 rounded-full ${state === 'speaking' ? 'bg-emerald-500 animate-pulse' : 'bg-slate-500'}`} />
            <span className="text-slate-200 text-sm font-mono uppercase tracking-wider">
                {state === 'disconnected' ? 'Offline' : state}
            </span>
        </div>
    );
}
