import pandas as pd
import pandas_ta as ta
import logging

logger = logging.getLogger(__name__)

def calculate_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies deep technical analysis to the provided historical OHLCV data.
    This replicates the powerful backend TA capabilities of TradingView.
    """
    if df.empty or len(df) < 50:
        logger.warning("Not enough data to calculate complex indicators.")
        return df

    logger.info("Applying Deep Technical Analysis to dataset...")

    # Ensure required columns exist
    required_cols = ['Open', 'High', 'Low', 'Close', 'Volume']
    if not all(col in df.columns for col in required_cols):
        logger.error(f"Missing required columns. Found: {df.columns}")
        return df

    # --- Trend Indicators ---
    # MACD (Moving Average Convergence Divergence)
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    
    # EMA (Exponential Moving Averages)
    df.ta.ema(length=20, append=True)
    df.ta.ema(length=50, append=True)
    df.ta.ema(length=200, append=True)

    # --- Momentum Indicators ---
    # RSI (Relative Strength Index)
    df.ta.rsi(length=14, append=True)
    
    # Stochastic Oscillator
    df.ta.stoch(append=True)

    # --- Volatility Indicators ---
    # Bollinger Bands
    df.ta.bbands(length=20, std=2, append=True)
    
    # ATR (Average True Range)
    df.ta.atr(length=14, append=True)

    # --- Volume Indicators ---
    # VWAP (Volume Weighted Average Price)
    # Note: Requires a datetime index or similar anchor, using simple fallback here if daily
    try:
        df.ta.vwap(append=True)
    except Exception as e:
        logger.warning(f"Could not calculate VWAP (likely missing intraday datetime index): {e}")

    logger.info("Technical Analysis calculations complete.")
    
    # Drop rows with NaNs generated by the rolling windows of indicators
    df.dropna(inplace=True)
    return df

if __name__ == "__main__":
    # Test execution
    import numpy as np
    
    # Create mock OHLCV data
    dates = pd.date_range("2023-01-01", periods=200)
    mock_data = {
        "Open": np.random.uniform(100, 150, 200),
        "High": np.random.uniform(150, 160, 200),
        "Low": np.random.uniform(90, 100, 200),
        "Close": np.random.uniform(100, 150, 200),
        "Volume": np.random.randint(1000, 10000, 200)
    }
    df = pd.DataFrame(mock_data, index=dates)
    
    result = calculate_technical_indicators(df)
    print("Columns after TA:")
    print(result.columns.tolist())
