version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # Update for your cameras (usually 64mb per camera)
    devices:
      # Requires a Google Coral USB Accelerator for fast AI detection
      # - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml
      - ./storage/frigate:/media/frigate
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./storage/mosquitto/data:/mosquitto/data
      - ./storage/mosquitto/log:/mosquitto/log

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
